---
groups:
  - name: bosh
    jobs:
      - unit-1.9
      - unit-2.1
      - integration-1.9-mysql
      - integration-1.9-postgres
      - integration-2.1-mysql
      - integration-2.1-postgres
      - publish-coverage
      - promote-candidate

  - name: 1.9
    jobs:
      - unit-1.9
      - integration-1.9-mysql
      - integration-1.9-postgres
      - publish-coverage
      - promote-candidate

  - name: 2.1
    jobs:
      - unit-2.1
      - integration-2.1-mysql
      - integration-2.1-postgres
      - publish-coverage
      - promote-candidate

  - name: mysql
    jobs:
      - unit-1.9
      - unit-2.1
      - integration-1.9-mysql
      - integration-2.1-mysql
      - publish-coverage
      - promote-candidate

  - name: postgres
    jobs:
      - unit-1.9
      - unit-2.1
      - integration-1.9-postgres
      - integration-2.1-postgres
      - publish-coverage
      - promote-candidate

jobs:
  - name: gate
    public: true
    serial: true
    plan:
      - {trigger: true, get: bosh-src}
      - task: gate
        file: bosh-src/ci/tasks/gate.yml

  - name: unit-1.9
    public: true
    serial: true
    plan:
      - {trigger: true, get: bosh-src, passed: [gate]}

      - task: test
        file: bosh-src/ci/tasks/test-unit.yml
        config:
          params:
            RUBY_VERSION: 1.9.3

  - name: unit-2.1
    public: true
    serial: true
    plan:
      - {trigger: true, get: bosh-src, passed: [gate]}

      - task: test
        file: bosh-src/ci/tasks/test-unit.yml
        config:
          params:
            RUBY_VERSION: 2.1.6

  - name: integration-1.9-mysql
    public: true
    serial: true
    plan:
      - {trigger: true, get: bosh-src, passed: [gate]}

      - task: test
        privileged: true
        file: bosh-src/ci/tasks/test-integration.yml
        config:
          params:
            DB:           mysql
            RUBY_VERSION: 1.9.3

  - name: integration-1.9-postgres
    public: true
    serial: true
    plan:
      - {trigger: true, get: bosh-src, passed: [gate]}

      - task: test
        privileged: true
        file:  bosh-src/ci/tasks/test-integration.yml
        config:
          params:
            DB:           postgresql
            RUBY_VERSION: 1.9.3

  - name: integration-2.1-mysql
    public: true
    serial: true
    plan:
      - {trigger: true, get: bosh-src, passed: [gate]}

      - task: test
        privileged: true
        file: bosh-src/ci/tasks/test-integration.yml
        config:
          params:
            DB:           mysql
            RUBY_VERSION: 2.1.6

  - name: integration-2.1-postgres
    public: true
    serial: true
    plan:
      - {trigger: true, get: bosh-src, passed: [gate]}

      - task: test
        privileged: true
        file: bosh-src/ci/tasks/test-integration.yml
        config:
          params:
            DB:           postgresql
            RUBY_VERSION: 2.1.6

  - name: publish-coverage
    public: true
    serial: true
    plan:
      - trigger: true
        passed: [integration-1.9-mysql, integration-2.1-mysql, integration-1.9-postgres, integration-2.1-postgres, unit-2.1, unit-1.9]
        get: bosh-src
      - task: publish
        file: bosh-src/ci/tasks/publish-coverage.yml
        config:
          params:
            CODECLIMATE_REPO_TOKEN: {{codeclimate_token}}

  - name: promote-candidate
    public: true
    serial: true
    plan:
      - trigger: true
        passed: [integration-1.9-mysql, integration-2.1-mysql, integration-1.9-postgres, integration-2.1-postgres, unit-2.1, unit-1.9]
        get: bosh-src

      - {put: bosh-candidate, params: {repository: bosh-src}}

resources:
  - name: bosh-src
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh.git
      branch: develop

  - name: bosh-candidate
    type: git
    source:
      uri: git@github.com:cloudfoundry/bosh.git
      branch: candidate
      private_key: {{github_deployment_key__bosh}}
